import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Providers } from "@/lib/providers/providers";
import AuthLoader from "@/components/AuthLoader";
import HeaderWrapper from "@/components/HeaderWrapper";
import GlobalLoadingOverlay from "@/components/GlobalLoadingOverlay";
import NavigationEvents from "@/lib/providers/NavigationEvents";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return ["en", "ko"].map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const locale = params.locale;

  return (
    <html lang={locale}>
      <head>
        <script src="https://js.tosspayments.com/v2/standard"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthLoader />
          <HeaderWrapper />
          <GlobalLoadingOverlay />
          <NavigationEvents />
          {children}
        </Providers>
      </body>
    </html>
  );
}
